A1, B1, C1 = input().split()
A, B, C = float(A1), float(B1), float(C1)
print(f"TRIANGULO: {A*C/2:.3f}")
print(f"CIRCULO: {3.14159*C**2:.3f}")
print(f"TRAPEZIO: {((A+B)*C)/2:.3f}")
print(f"QUADRADO: {B*B:.3f}")
print(f"RETANGULO: {A*B:.3f}")
